from pathlib import Path
p=Path('backend/app/tomtom_traffic.py')
if not p.exists(): raise SystemExit('[FAIL] backend/app/tomtom_traffic.py not found')
s=p.read_text(encoding='utf-8')
old='''                if response.status_code >= 400:\n                    category, retryable, friendly = classify_http_error(RuntimeError(), response.status_code)\n                    err = ProviderRequestError(\n                        f"{friendly} (HTTP {response.status_code})",\n                        category=category,\n                        retryable=retryable,\n                        status_code=response.status_code,\n                        attempts=attempt,\n                    )'''
new='''                if response.status_code >= 400:\n                    body_text = response.text or ""\n                    body_lower = body_text.lower()\n                    if response.status_code in (403, 429) and (\n                        "insufficientfunds" in body_lower or "insufficient funds" in body_lower\n                        or "quota" in body_lower or "credit" in body_lower\n                    ):\n                        category, retryable, friendly = ("quota_exhausted", False, "Traffic provider allowance/credit is exhausted.")\n                    else:\n                        category, retryable, friendly = classify_http_error(RuntimeError(), response.status_code)\n                    err = ProviderRequestError(\n                        f"{friendly} (HTTP {response.status_code})",\n                        category=category,\n                        retryable=retryable,\n                        status_code=response.status_code,\n                        attempts=attempt,\n                    )'''
if old in s: s=s.replace(old,new)
elif 'body_lower = body_text.lower()' not in s: raise SystemExit('[FAIL] TomTom HTTP block changed; refusing unsafe patch')
if '# ITICAS_STAGE08_AUTHORIZED_KEYRING' not in s:
    s += '''\n\n# ITICAS_STAGE08_AUTHORIZED_KEYRING\nfrom .tomtom_keyring import credentials as _tt_credentials, safe_status as tomtom_keyring_status\n_ITICAS_STAGE08_PREVIOUS_FETCH_FLOW = TomTomTrafficClient.fetch_flow\nasync def _iticas_stage08_keyring_fetch_flow(self, latitude, longitude):\n    creds=_tt_credentials()\n    if not creds: return await _ITICAS_STAGE08_PREVIOUS_FETCH_FLOW(self, latitude, longitude)\n    last_error=None\n    for index,cred in enumerate(creds):\n        candidate=TomTomTrafficClient(api_key=cred.key, timeout=self.timeout)\n        try:\n            return await _ITICAS_STAGE08_PREVIOUS_FETCH_FLOW(candidate, latitude, longitude)\n        except ProviderRequestError as exc:\n            last_error=exc\n            if getattr(exc,"category","")=="authentication_failure" and index+1<len(creds):\n                continue\n            raise\n    if last_error: raise last_error\n    raise ProviderNotConfigured("No usable TomTom credential is configured.")\nTomTomTrafficClient.fetch_flow=_iticas_stage08_keyring_fetch_flow\n'''
p.write_text(s,encoding='utf-8')
print('[PASS] Stage08 TomTom keyring installed')
